// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pingpong.proto

/*
Package pingpong is a generated protocol buffer package.

It is generated from these files:
	pingpong.proto

It has these top-level messages:
	PingRequest
	PongReply
	PongReply2
*/
package pingpong

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	Sender string `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

type PongReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PongReply) Reset()                    { *m = PongReply{} }
func (m *PongReply) String() string            { return proto.CompactTextString(m) }
func (*PongReply) ProtoMessage()               {}
func (*PongReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PongReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PongReply2 struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PongReply2) Reset()                    { *m = PongReply2{} }
func (m *PongReply2) String() string            { return proto.CompactTextString(m) }
func (*PongReply2) ProtoMessage()               {}
func (*PongReply2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PongReply2) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "pingpong.PingRequest")
	proto.RegisterType((*PongReply)(nil), "pingpong.PongReply")
	proto.RegisterType((*PongReply2)(nil), "pingpong.PongReply2")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PingPong service

type PingPongClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongReply, error)
	NoPing(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*PongReply, error)
}

type pingPongClient struct {
	cc *grpc.ClientConn
}

func NewPingPongClient(cc *grpc.ClientConn) PingPongClient {
	return &pingPongClient{cc}
}

func (c *pingPongClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongReply, error) {
	out := new(PongReply)
	err := grpc.Invoke(ctx, "/pingpong.PingPong/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingPongClient) NoPing(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*PongReply, error) {
	out := new(PongReply)
	err := grpc.Invoke(ctx, "/pingpong.PingPong/NoPing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PingPong service

type PingPongServer interface {
	Ping(context.Context, *PingRequest) (*PongReply, error)
	NoPing(context.Context, *google_protobuf1.Empty) (*PongReply, error)
}

func RegisterPingPongServer(s *grpc.Server, srv PingPongServer) {
	s.RegisterService(&_PingPong_serviceDesc, srv)
}

func _PingPong_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpong.PingPong/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingPong_NoPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServer).NoPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpong.PingPong/NoPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServer).NoPing(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingPong_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pingpong.PingPong",
	HandlerType: (*PingPongServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingPong_Ping_Handler,
		},
		{
			MethodName: "NoPing",
			Handler:    _PingPong_NoPing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pingpong.proto",
}

func init() { proto.RegisterFile("pingpong.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc8, 0xcc, 0x4b,
	0x2f, 0xc8, 0xcf, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0xa5, 0x64,
	0xd2, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b,
	0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x8a, 0x21, 0xea, 0xa4, 0xa4, 0xa1, 0xb2, 0x60, 0x5e, 0x52, 0x69,
	0x9a, 0x7e, 0x6a, 0x6e, 0x41, 0x49, 0x25, 0x44, 0x52, 0x49, 0x95, 0x8b, 0x3b, 0x20, 0x33, 0x2f,
	0x3d, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x8c, 0x8b, 0xad, 0x38, 0x35, 0x2f, 0x25,
	0xb5, 0x48, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xca, 0x53, 0x52, 0xe5, 0xe2, 0x0c, 0xc8,
	0x07, 0x29, 0x2b, 0xc8, 0xa9, 0x14, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f,
	0x85, 0xaa, 0x82, 0x71, 0x95, 0xd4, 0xb8, 0xb8, 0xe0, 0xca, 0x8c, 0x70, 0xab, 0x33, 0x9a, 0xc6,
	0xc8, 0xc5, 0x01, 0xb2, 0x16, 0xa4, 0x58, 0xc8, 0x85, 0x8b, 0x05, 0xc4, 0x16, 0x12, 0xd5, 0x83,
	0x7b, 0x10, 0xc9, 0x49, 0x52, 0xc2, 0x48, 0xc2, 0x30, 0xb3, 0x95, 0x04, 0x9a, 0x2e, 0x3f, 0x99,
	0xcc, 0xc4, 0xa5, 0xc4, 0xaa, 0x0f, 0x92, 0xb4, 0x62, 0xd4, 0x12, 0x72, 0xe1, 0x62, 0xf3, 0xcb,
	0x07, 0x9b, 0x23, 0xa6, 0x07, 0xf1, 0xb0, 0x1e, 0xcc, 0xc3, 0x7a, 0xae, 0x20, 0x0f, 0x63, 0x37,
	0x88, 0x17, 0x6c, 0x10, 0xbb, 0x10, 0xab, 0x3e, 0x48, 0x22, 0x89, 0x0d, 0xac, 0xc7, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x50, 0xad, 0xd0, 0xd8, 0x6c, 0x01, 0x00, 0x00,
}
